{
 "title": "Postgresql",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_up{instance=\"database:9187\"}"
    }
   ]
  },
  {
   "title": "Size",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_database_size{instance=\"database:9187\",datname=\"toto\"}"
    }
   ]
  },
  {
   "title": "Locks",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(pg_locks_count{instance=\"database:9187\", datname=\"toto\"})"
    }
   ]
  },
  {
   "title": "Deadlocks",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "pg_stat_database_deadlocks{datname=\"toto\",instance=\"database:9187\"}"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_fetched{datname=\"toto\",instance=\"database:9187\"}",
     "legendFormat": "Fetch"
    },
    {
     "expr": "pg_stat_database_tup_returned{datname=\"toto\",instance=\"database:9187\"}",
     "legendFormat": "Return"
    },
    {
     "expr": "pg_stat_database_tup_inserted{datname=\"toto\",instance=\"database:9187\"}",
     "legendFormat": "Insert"
    },
    {
     "expr": "pg_stat_database_tup_updated{datname=\"toto\",instance=\"database:9187\"}",
     "legendFormat": "Update"
    },
    {
     "expr": "pg_stat_database_tup_deleted{datname=\"toto\",instance=\"database:9187\"}",
     "legendFormat": "Delete"
    }
   ]
  },
  {
   "title": "Activity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=\"toto\",instance=\"database:9187\",job=\"node.postgres\",state=\"active\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "pg_stat_activity_count{datname=\"toto\",instance=\"database:9187\",job=\"node.postgres\",state=\"disabled\"}",
     "legendFormat": "Disabled"
    },
    {
     "expr": "pg_stat_activity_count{datname=\"toto\",instance=\"database:9187\",job=\"node.postgres\",state=\"fastpath function call\"}",
     "legendFormat": "Fastpath"
    },
    {
     "expr": "pg_stat_activity_count{datname=\"toto\",instance=\"database:9187\",job=\"node.postgres\",state=\"idle\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "pg_stat_activity_count{datname=\"toto\",instance=\"database:9187\",job=\"node.postgres\",state=\"idle in transaction\"}",
     "legendFormat": "Idle in transaction"
    },
    {
     "expr": "pg_stat_activity_count{datname=\"toto\",instance=\"database:9187\",job=\"node.postgres\",state=\"idle in transaction (aborted)\"}",
     "legendFormat": "Idle in transaction (aborted)"
    }
   ]
  }
 ]
}