{
 "title": "System - Webapp",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"webapp:9100\"} - node_boot_time_seconds{instance=\"webapp:9100\"}"
    }
   ]
  },
  {
   "title": "System load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load5{instance=\"webapp:9100\"}",
     "legendFormat": "Load"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{instance=\"webapp:9100\", mode=\"system\"}[1m])",
     "legendFormat": "Core {{cpu}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"webapp:9100\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"webapp:9100\"} - node_memory_MemFree_bytes{instance=\"webapp:9100\"} - node_memory_Cached_bytes{instance=\"webapp:9100\"} - node_memory_Buffers_bytes{instance=\"webapp:9100\"} - node_memory_Slab_bytes{instance=\"webapp:9100\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"webapp:9100\"} - node_memory_SwapFree_bytes{instance=\"webapp:9100\"})",
     "legendFormat": "Swap"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=\"webapp:9100\"}[1m]) or irate(node_disk_reads_completed{instance=\"webapp:9100\"}[1m])",
     "legendFormat": "Reads {{device}}"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=\"webapp:9100\"}[1m]) or irate(node_disk_writes_completed{instance=\"webapp:9100\"}[1m])",
     "legendFormat": "Writes {{device}}"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{instance=\"webapp:9100\", device!=\"lo\"}[1m]))",
     "legendFormat": "Up"
    },
    {
     "expr": "sum(irate(node_network_receive_bytes_total{instance=\"webapp:9100\", device!=\"lo\"}[1m]))",
     "legendFormat": "Down"
    }
   ]
  }
 ]
}